# render.yaml

services:
  - type: web
    name: fastapi-interview-api
    env: python
    branch: testing
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
