# render.yaml

services:
  - type: web
    name: fastapi-interview-api
    env: python
    branch: testing
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7

